### PR TITLE
Fix Ubuntu 22.04 support

### PR DESCRIPTION
**Pull request by mikz**
There is no package lib32gcc1, just lib32gcc1-s1.

That is also described in the steamcmd wiki 
https://developer.valvesoftware.com/wiki/SteamCMD#Manually

### CODE REVIEW

**Comment by andriivitiv** [comment]
Thanks. Released `v1.1.2`.

**Comment by mikz** [comment]
Thank you! 👍

**Comment by mastef** [comment]
This breaks existing github actions that rely on Ubuntu 18.04 - since that one doesn't have `lib32gcc1-s1`. It breaks existing workflows that rely e.g. on game-ci unity builders, since those still run on Ubuntu 18.

Fix for that is to only use version `v1.1.1`

**Comment by mikz** [comment]
Maybe it would be worth to bump the major version to indicate the breaking change then.

**Comment by mastef** [comment]
@mikz or just try installing both while ignoring unavailable ones with : 

```js
await exec.exec('sudo', ['apt-get', '--yes', '--ignore-missing', 'install', 'lib32gcc1', 'lib32gcc-s1']);
```

After all the action promises steam-cmd for actions - and not for a specific ubuntu version.

**Comment by mikz** [comment]
@mastef That is smart! Didn't know you can do that.

Are you going to make a PR?

And if you add specific ubuntu version you want to keep working to https://github.com/CyberAndrii/setup-steamcmd/blob/b786e0da44db3d817e66fa3910a9560cb28c9323/.github/workflows/integration.yml#L18 then it would run the tests for it I think.

**Pull request merged**
